name: 🐛 Bug Report
description: Report a bug in VelocityTrader
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug in VelocityTrader! Please fill out this form to help us understand and reproduce the issue.

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please verify these steps before submitting
      options:
        - label: I have searched for existing issues that describe this bug
          required: true
        - label: I have checked that this issue is related to VelocityTrader core functionality
          required: true
        - label: I have read the documentation and troubleshooting guide
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Data Pipeline (MT5 Connection)
        - Agent System (BERSERKER/SNIPER)
        - Trading Engine
        - Performance Dashboard
        - Logging System
        - Configuration
        - Testing Framework
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System crash, data loss, security issue)
        - High (Major functionality broken)
        - Medium (Minor functionality broken)
        - Low (Cosmetic issue, minor inconvenience)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Run command '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      placeholder: |
        - OS: [e.g. Windows 11, Ubuntu 22.04]
        - Python Version: [e.g. 3.11.5]
        - VelocityTrader Version: [e.g. 1.0.0]
        - MT5 Terminal Version: [e.g. 5.0.45]
        - Hardware: [e.g. AMD 5950X, 128GB RAM]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please copy and paste any relevant log output
      placeholder: Paste logs here...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information...

  - type: checkboxes
    id: security
    attributes:
      label: Security Consideration
      description: Please check if this bug involves security concerns
      options:
        - label: This bug involves potential security vulnerabilities
        - label: This bug exposes sensitive trading data
        - label: This bug affects MT5 connection security